# Generated by Django 3.1.4 on 2021-06-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='company_size',
            field=models.IntegerField(null=True, verbose_name='Size of the company'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='email',
            field=models.EmailField(max_length=200, null=True, verbose_name='your professional email '),
        ),
        migrations.AddField(
            model_name='quizz',
            name='maturity',
            field=models.IntegerField(null=True, verbose_name='Maturity for 1 (total beginners) to 5 (experts)'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='sprint_time',
            field=models.IntegerField(null=True, verbose_name='Sprint Time in day'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='your professional email '),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='teamsize',
            field=models.IntegerField(null=True, verbose_name='Team Size'),
        ),
    ]
