# Generated by Django 3.1.4 on 2021-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_remove_quizz_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='company_size',
            field=models.IntegerField(null=True, verbose_name='Company size'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='maturity',
            field=models.IntegerField(null=True, verbose_name='Agile maturity from 1 (total beginners) to 5 (experts)'),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='sprint_time',
            field=models.IntegerField(null=True, verbose_name='Sprint duration in days'),
        ),
    ]
